version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World! bobby'
  sally:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World! sally'
workflow:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally

