version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo 'npm install'
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo 'testing stuff'
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:latest
    steps:    
      - checkout
      - run: echo "helllloo!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere

